desc 'Run Console'
task :console do |t, args|
  env = ENV["APP_ENV"] || 'development'

  puts "Loading #{env} environment..."
  require './demo01/job'
  require 'pry'

  job01 = Job.new
  job01.current_state

  ARGV.clear
  binding.pry
end

task default: :console
